### ISSUE TITLE
i18n not applying in iOS

### ISSUE THREAD

**Issue by easyhooon** [wisemuji/compose-would-you-rather-game#2]
**Affected Device(s):**
iPhone 15 Pro iOS 17.4(emulator) 

**Describe the Bug:**
Even when the language is set to Korean in the iOS app, the question and result content within the game appears in English.

|Game|Result
|:-----:|:-----:|
|<img width="240" src="https://github.com/user-attachments/assets/09cc3739-d4e3-4b72-957f-a1a1bcdb94ea">|<img width="240" src="https://github.com/user-attachments/assets/6dde37b0-cf31-444b-9e8f-22d5fe55cc60">|

**Expected Behavior:**
When the language is set to Korean, the content language should be displayed in Korean.

**Comment by wisemuji** [comment]
@easyhooon Thank you for the report! I'll make a fix and mention you in the PR.

**Comment by wisemuji** [comment]
Thank you for your contribution! 🤗
